#ifndef YJDRAGGRID_COMPAT_DRAGGRIDLAYOUT_H
#define YJDRAGGRID_COMPAT_DRAGGRIDLAYOUT_H

#include <YJDragGrid/DragGridLayout.h>

using YJDragGrid::DragGridLayout;

#endif // YJDRAGGRID_COMPAT_DRAGGRIDLAYOUT_H
