#ifndef YJDRAGGRID_COMPAT_DRAGGRIDWIDGET_H
#define YJDRAGGRID_COMPAT_DRAGGRIDWIDGET_H

#include <YJDragGrid/DragGridWidget.h>

using YJDragGrid::DragGridWidget;

#endif // YJDRAGGRID_COMPAT_DRAGGRIDWIDGET_H
